[[constraint]]
  name = "github.com/astaxie/beego"
  version = "1.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/beego/samples"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"
